/**
 * Report Data Generator
 * Scans the regulatory-docs/ folder and generates reports-data.js
 * Run: node generate-reports.js
 * Watch mode: node generate-reports.js --watch
 */
const fs = require('fs');
const path = require('path');

const DOCS_DIR = path.join(__dirname, 'regulatory-docs');
const OUTPUT_FILE = path.join(__dirname, 'reports-data.js');
const META_FILE = path.join(DOCS_DIR, 'reports.json');

// Detect report type from filename
function detectType(filename) {
    const lower = filename.toLowerCase();
    if (lower.includes('annual') || lower.includes('year') || lower.includes('年度')) return 'annual';
    if (lower.includes('q1') || lower.includes('q2') || lower.includes('q3') || lower.includes('q4') ||
        lower.includes('quarter') || lower.includes('quarterly') || lower.includes('季度')) return 'quarterly';
    if (lower.includes('audit') || lower.includes('audited') || lower.includes('審計')) return 'audit';
    if (lower.includes('sec') || lower.includes('form adv') || lower.includes('regulatory') ||
        lower.includes('申報') || lower.includes('監管')) return 'regulatory';
    if (lower.includes('investor') || lower.includes('presentation') || lower.includes('day') ||
        lower.includes('投資者')) return 'investor';
    return 'other';
}

// Format file size
function formatSize(bytes) {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / 1048576).toFixed(1) + ' MB';
}

// Format date
function formatDate(date) {
    const d = new Date(date);
    const months = ['January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December'];
    return `${months[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`;
}

// Get title from filename (remove extension, clean up)
function titleFromFilename(filename) {
    let name = filename.replace(/\.[^/.]+$/, ''); // remove extension
    name = name.replace(/[-_]/g, ' '); // replace dashes/underscores with spaces
    name = name.replace(/\s+/g, ' ').trim(); // collapse spaces
    // Capitalize words
    name = name.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
    return name;
}

function generate() {
    // Load metadata overrides
    let meta = {};
    if (fs.existsSync(META_FILE)) {
        try {
            meta = JSON.parse(fs.readFileSync(META_FILE, 'utf-8'));
        } catch (e) {
            console.warn('Warning: Could not parse reports.json, using defaults.');
        }
    }

    const reports = [];

    // Scan year folders
    const yearDirs = fs.readdirSync(DOCS_DIR).filter(name => {
        const full = path.join(DOCS_DIR, name);
        return fs.statSync(full).isDirectory() && /^\d{4}$/.test(name);
    }).sort((a, b) => b - a); // newest first

    for (const year of yearDirs) {
        const yearPath = path.join(DOCS_DIR, year);
        const files = fs.readdirSync(yearPath).filter(name => {
            const full = path.join(yearPath, name);
            return fs.statSync(full).isFile() && !name.startsWith('.');
        });

        for (const file of files) {
            const filePath = path.join(yearPath, file);
            const stat = fs.statSync(filePath);
            const key = year + '/' + file;

            // Check for metadata override
            const override = meta[key] || meta[file] || {};

            reports.push({
                year: year,
                filename: file,
                path: 'regulatory-docs/' + year + '/' + encodeURIComponent(file),
                title: override.title || titleFromFilename(file),
                type: override.type || detectType(file),
                date: override.date || formatDate(stat.mtime),
                size: formatSize(stat.size),
                description: override.description || ''
            });
        }
    }

    // Sort: newest first by date
    reports.sort((a, b) => {
        const da = new Date(a.date);
        const db = new Date(b.date);
        return db - da;
    });

    // Generate JS output
    const output = `// Auto-generated by generate-reports.js on ${new Date().toISOString()}
// DO NOT EDIT MANUALLY - Run "node generate-reports.js" to regenerate

var REGULATORY_REPORTS = ${JSON.stringify(reports, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
    console.log(`Generated reports-data.js with ${reports.length} report(s).`);

    // List reports
    for (const r of reports) {
        console.log(`  [${r.year}] ${r.title} (${r.type}) - ${r.size}`);
    }
}

// --- Main ---
const args = process.argv.slice(2);

if (args.includes('--watch') || args.includes('-w')) {
    console.log('Watching ' + DOCS_DIR + ' for changes...');
    console.log('Press Ctrl+C to stop.\n');
    generate();

    // Watch for changes
    let timeout;
    const watchHandler = (eventType, filename) => {
        if (filename && !filename.startsWith('.')) {
            clearTimeout(timeout);
            timeout = setTimeout(() => {
                console.log('\nChange detected, regenerating...');
                generate();
                console.log('Watching for changes...');
            }, 500);
        }
    };

    // Watch the docs directory recursively
    const watchRecursive = (dir) => {
        fs.watch(dir, { recursive: false }, watchHandler);
        // Also watch subdirectories
        fs.readdirSync(dir).forEach(name => {
            const full = path.join(dir, name);
            if (fs.statSync(full).isDirectory()) {
                watchRecursive(full);
            }
        });
    };
    watchRecursive(DOCS_DIR);

    // Keep process alive
    process.stdin.resume();
} else {
    generate();
}
