// Language switching logic
(function() {
    const translations = {
        en: {
            // Nav
            'nav.home': 'Home',
            'nav.products': 'Products',
            'nav.about': 'About Us',
            'nav.services': 'Services',
            'nav.disclosure': 'Disclosure',
            'nav.contact': 'Contact',

            // Hero - index
            'hero.heading': 'Innovating <span class="highlight">Future</span> Finance',
            'hero.subtitle': 'Apex Capital is a leading fund management company specializing in quantitative strategies, AI-driven investments, and sustainable growth opportunities.',
            'hero.cta': 'Explore Our Vision',
            'hero.cta2': 'View Full Prospectus <i class="fas fa-arrow-right"></i>',
            'hero.stat1.label': 'AUM (RMB)',
            'hero.stat1.unit': 'B',
            'hero.stat2.label': 'Annual Return Target',
            'hero.stat3.label': 'Established',
            'hero.card.title': 'Core Product',
            'hero.card.mgmtFee': 'Mgmt Fee',
            'hero.card.custodyFee': 'Custody Fee',
            'hero.card.min': 'Min Invest',
            'hero.card.purchase': 'Purchase',
            'hero.card.daily': 'Daily Open',

            // Products section
            'products.tag': 'Core Products',
            'products.title': 'Our Products',
            'products.subtitle': 'Focused on bills and bonds, delivering lasting value through stable strategies.',
            'products.featured.badge': 'Flagship Product',
            'products.featured.desc': '≥90% allocation to high-grade credit, interest rate bonds & interbank CDs. Leveraging Fujian regional advantages to select AAA+ notes from state-owned banks and institutional platforms. Target annualized return 13.5%.',
            'products.fph1.title': 'AAA+ Credit Rating',
            'products.fph1.desc': 'State-owned banks & institutional platforms only',
            'products.fph2.title': '10%—13.5% Annualized',
            'products.fph2.desc': 'Drawdown control ≤ 3%',
            'products.fph3.title': 'T+6 Flexible Redemption',
            'products.fph3.desc': 'No redemption fee after 30 days',
            'products.fph4.title': '$5,000 Minimum',
            'products.fph4.desc': 'Low entry, suitable for regular plans.',

            // Fund facts (shared)
            'fund.facts.code': 'Product Code',
            'fund.facts.redemption.short': '≥30d free',
            'fund.manager.label': 'Manager',
            'fund.manager.short': 'FJ Shang Jin Nong Sui',

            // Fund tags
            'fund.tag1': 'Hybrid',
            'fund.tag2': 'Note-Type',
            'fund.tag3': 'Open-Ended',
            'fund.tag4': 'Daily Trading',

            // Services section
            'services.tag': 'More Services',
            'services.title': 'Professional Fund Management',
            'services.card1.title': 'Quantitative Strategies',
            'services.card1.desc': 'Proprietary algorithms and machine learning models identify market inefficiencies and generate alpha.',
            'services.card2.title': 'Sustainable Investing',
            'services.card2.desc': 'ESG-integrated portfolios that align financial performance with positive environmental and social impact.',
            'services.card3.title': 'Risk-Managed Solutions',
            'services.card3.desc': 'Dynamic hedging and portfolio construction designed to protect capital while capturing upside potential.',
            'services.learnMore': 'Learn More',

            // Section tags
            'about.tag': 'About Us',
            'disclosure.tag': 'Disclosure',
            'contact.tag': 'Contact',

            // About - index
            'about.title': 'Our Core Business',
            'about.subtitle': 'We combine cutting-edge technology with deep financial expertise to deliver superior returns for our clients.',
            'about.card1.title': 'Quantitative Strategies',
            'about.card1.desc': 'Proprietary algorithms and machine learning models identify market inefficiencies and generate alpha across asset classes.',
            'about.card2.title': 'Sustainable Investing',
            'about.card2.desc': 'ESG-integrated portfolios that align financial performance with positive environmental and social impact.',
            'about.card3.title': 'Risk-Managed Solutions',
            'about.card3.desc': 'Dynamic hedging and portfolio construction designed to protect capital while capturing upside potential.',

            // Disclosure - index
            'disclosure.title': 'Company Disclosures',
            'disclosure.subtitle': 'Transparency and compliance are at the heart of our operations.',
            'disclosure.card1.title': 'Regulatory Filings',
            'disclosure.card1.li1': 'Annual Report 2025 – ',
            'disclosure.card1.li1.link': 'Download PDF',
            'disclosure.card1.li2': 'Quarterly Performance Update Q1 2026 – ',
            'disclosure.card1.li2.link': 'View Online',
            'disclosure.card1.li3': 'SEC Form ADV – ',
            'disclosure.card1.li3.link': 'Access Here',
            'disclosure.card1.li4': 'Audited Financial Statements – ',
            'disclosure.card1.li4.link': 'Download',
            'disclosure.card1.more': 'View More Documents',
            'disclosure.card2.title': 'Compliance & Governance',
            'disclosure.card2.li1': 'Code of Ethics – ',
            'disclosure.card2.li1.link': 'Read',
            'disclosure.card2.li2': 'Privacy Policy – ',
            'disclosure.card2.li2.link': 'Learn More',
            'disclosure.card2.li3': 'Conflict of Interest Policy – ',
            'disclosure.card2.li3.link': 'View',
            'disclosure.card2.li4': 'Anti-Money Laundering Statement – ',
            'disclosure.card2.li4.link': 'Details',
            'disclosure.card3.title': 'Public Announcements',
            'disclosure.card3.li1': 'New Fund Launch: Quantum Green Energy Fund – ',
            'disclosure.card3.li1.link': 'Press Release',
            'disclosure.card3.li2': 'Partnership with Tech Innovation Hub – ',
            'disclosure.card3.li2.link': 'Announcement',
            'disclosure.card3.li3': 'Industry Conference Participation – ',
            'disclosure.card3.li3.link': 'Schedule',
            'disclosure.card3.li4': 'CEO Keynote: Future of Digital Assets – ',
            'disclosure.card3.li4.link': 'Watch Recording',

            // Compliance Pages
            'comp.ethics.title': 'Code of Ethics',
            'comp.ethics.date': '<strong>Effective Date:</strong> January 1, 2025',
            'comp.ethics.intro': 'Apex Capital and its managed funds are committed to conducting business with the highest ethical standards. This Code of Ethics establishes behavioral benchmarks for all employees, management, and partners, ensuring every decision prioritizes investor interests.',
            'comp.ethics.h1': '1. Integrity & Honesty',
            'comp.ethics.c1': 'All personnel must adhere to the principle of good faith. Fraud, misrepresentation, or misleading statements in any form are strictly prohibited. All investment advice, product communications, and client interactions must be truthful, accurate, and complete.',
            'comp.ethics.h2': '2. Investor Interests First',
            'comp.ethics.c2': '<ul><li>Place investor interests above those of the firm and individuals at all times</li><li>Treat all investors fairly; preferential treatment for select investors is prohibited</li><li>Trade execution must follow best-execution principles to secure optimal pricing at minimum cost</li></ul>',
            'comp.ethics.h3': '3. Conflict of Interest Management',
            'comp.ethics.c3': 'All personnel must proactively disclose any actual or potential conflicts of interest, including but not limited to personal investments, external business interests, and familial relationships involving counterparties. See the Conflict of Interest Policy for details.',
            'comp.ethics.h4': '4. Insider Trading Prohibition',
            'comp.ethics.c4': 'The use of material non-public information for personal trading or its disclosure to others is strictly prohibited. All employees must comply with trade reporting requirements and are subject to compliance review.',
            'comp.ethics.h5': '5. Gifts & Entertainment',
            'comp.ethics.c5': 'No gifts, hospitality, or other benefits that may influence—or appear to influence—business decisions may be accepted. The value of any single gift accepted must not exceed RMB 500 and must be reported to the Compliance Department.',
            'comp.ethics.h6': '6. Whistleblower Protection',
            'comp.ethics.c6': 'Any person who becomes aware of conduct violating this Code may report it through confidential channels to the Compliance Department. The firm strictly prohibits retaliation of any kind against good-faith whistleblowers.',
            'comp.ethics.h7': '7. Violations & Enforcement',
            'comp.ethics.c7': 'Violations of this Code will result in disciplinary action, including but not limited to warnings, suspension, termination of employment, and referral to regulatory authorities in serious cases.',
            'comp.ethics.footer': '<em>This Code is reviewed annually by the Compliance Committee under the Board of Directors.</em>',

            'comp.privacy.title': 'Privacy Policy',
            'comp.privacy.date': '<strong>Effective Date:</strong> January 1, 2025',
            'comp.privacy.intro': 'Apex Capital ("we," "us") values your privacy. This Privacy Policy describes how we collect, use, store, and protect your personal data.',
            'comp.privacy.h1': '1. Data Collection',
            'comp.privacy.c1': 'We may collect the following categories of personal data:<ul><li><strong>Identity Data:</strong> name, ID number, passport number, date of birth</li><li><strong>Contact Data:</strong> address, telephone number, email address</li><li><strong>Financial Data:</strong> bank account information, proof of income, asset position, investment experience</li><li><strong>Transaction Data:</strong> subscription and redemption records, holding information</li><li><strong>Due Diligence Data:</strong> information required for anti-money laundering (AML) and know-your-customer (KYC) procedures</li></ul>',
            'comp.privacy.h2': '2. Data Usage',
            'comp.privacy.c2': 'Your personal data is used solely for the following purposes:<ul><li>Processing fund subscriptions, redemptions, and distributions</li><li>Fulfilling legal and regulatory obligations (including AML screening)</li><li>Providing client service and product updates</li><li>Risk management and internal audit</li></ul>',
            'comp.privacy.h3': '3. Data Sharing',
            'comp.privacy.c3': 'We do not sell your personal data to third parties. Data may be shared only in the following circumstances:<ul><li>With regulators, exchanges, and law enforcement as required by law</li><li>With service partners (e.g., custodian banks, auditors) bound by equivalent confidentiality obligations</li><li>With your explicit consent in other situations</li></ul>',
            'comp.privacy.h4': '4. Data Security',
            'comp.privacy.c4': 'We employ reasonable technical and organizational measures to protect your personal data, including data encryption, access controls, and periodic security audits. Data is stored on domestic servers; cross-border transfers require compliance approval.',
            'comp.privacy.h5': '5. Data Retention',
            'comp.privacy.c5': 'Personal data is retained for a minimum of 7 years following the termination of the business relationship, in accordance with regulatory requirements. Data is securely destroyed upon expiry of the retention period.',
            'comp.privacy.h6': '6. Your Rights',
            'comp.privacy.c6': '<ul><li>Access and correct your personal data</li><li>Restrict or object to data processing</li><li>Withdraw consent (without affecting the lawfulness of prior processing)</li><li>Lodge a complaint with the relevant supervisory authority</li></ul>',
            'comp.privacy.h7': '7. Contact Us',
            'comp.privacy.c7': 'For privacy-related inquiries, please contact the Compliance Department:<br>Email: longvv810@gmail.com',

            'comp.conflict.title': 'Conflict of Interest Policy',
            'comp.conflict.date': '<strong>Effective Date:</strong> January 1, 2025',
            'comp.conflict.intro': 'Apex Capital is committed to identifying, managing, and disclosing all actual and potential conflicts of interest to ensure investor interests are not compromised.',
            'comp.conflict.h1': '1. Types of Conflicts',
            'comp.conflict.c1': 'The following are potential conflict-of-interest scenarios in our business:<ul><li><strong>Personal Trading:</strong> overlap between employee personal investments and fund holdings</li><li><strong>Related-Party Transactions:</strong> transactions involving affiliated entities (e.g., the manager or its subsidiaries)</li><li><strong>Soft Commissions:</strong> accepting research services or other benefits from counterparties</li><li><strong>Multiple Roles:</strong> the same individual serving multiple funds or clients simultaneously</li><li><strong>Gifts & Entertainment:</strong> accepting favors that may impair independent judgment</li><li><strong>External Appointments:</strong> employees holding positions at external organizations</li></ul>',
            'comp.conflict.h2': '2. Identification & Disclosure',
            'comp.conflict.c2': '<ul><li>New hires must complete a conflict-of-interest declaration within 30 days of onboarding</li><li>Existing employees must update their conflict-of-interest declaration annually</li><li>Any event that may constitute a conflict of interest must be proactively reported within 5 business days</li><li>Investment decision-makers must pre-clear personal trading plans</li></ul>',
            'comp.conflict.h3': '3. Management Measures',
            'comp.conflict.c3': '<ul><li><strong>Information Barriers:</strong> investment decision-making, trade execution, and settlement functions are strictly segregated</li><li><strong>Restricted List:</strong> the Compliance Department maintains a restricted securities list; relevant personnel are prohibited from trading those securities</li><li><strong>Independent Approval:</strong> related-party transactions require approval from the independent Risk Management Committee</li><li><strong>Fair Allocation:</strong> trading opportunities are allocated fairly based on the best-interest principle for clients</li><li><strong>Compensation Design:</strong> remuneration structures must not incentivize excessive risk-taking or harm to investor interests</li></ul>',
            'comp.conflict.h4': '4. Disclosure',
            'comp.conflict.c4': 'Conflicts that cannot be adequately managed through internal mechanisms will be clearly and fully disclosed to affected investors. The relevant business may proceed only after obtaining written consent.',
            'comp.conflict.h5': '5. Oversight & Enforcement',
            'comp.conflict.c5': 'The Compliance Department conducts an independent review of this Policy annually. Violations are handled in accordance with the Code of Ethics.',

            'comp.aml.title': 'Anti-Money Laundering Statement',
            'comp.aml.date': '<strong>Effective Date:</strong> January 1, 2025',
            'comp.aml.intro': 'Apex Capital strictly complies with applicable anti-money laundering (AML) and counter-terrorist financing (CFT) laws and regulations. We are committed to safeguarding the integrity of the financial system and preventing the inflow of illicit funds.',
            'comp.aml.h1': '1. Regulatory Basis',
            'comp.aml.c1': 'This AML program is established in accordance with:<ul><li>The Anti-Money Laundering Law of the People\'s Republic of China</li><li>The Administrative Regulations on Anti-Money Laundering for Financial Institutions</li><li>The Measures for the Administration of Financial Institutions\' Reporting of Large-Value and Suspicious Transactions</li><li>Relevant Financial Action Task Force (FATF) Recommendations</li></ul>',
            'comp.aml.h2': '2. Customer Due Diligence (CDD)',
            'comp.aml.c2': 'All investors must complete the following due diligence procedures before account opening:<ul><li>Verification of identity documents (individuals: national ID / passport; entities: business license, ownership structure)</li><li>Identification of ultimate beneficial owners (UBOs), penetrating through to natural persons holding 25% or more of equity interests</li><li>Understanding of the source of funds and wealth background</li><li>Application of simplified or enhanced due diligence based on risk rating</li></ul>',
            'comp.aml.h3': '3. Transaction Monitoring',
            'comp.aml.c3': '<ul><li>Large-value reporting for single or aggregated cash transactions exceeding RMB 50,000</li><li>Suspicious transactions reported within 24 hours to the China Anti-Money Laundering Monitoring and Analysis Center</li><li>Enhanced scrutiny of transactions involving high-risk countries or regions</li><li>Monitoring of unusual patterns such as frequent subscriptions/redemptions and structured transactions</li></ul>',
            'comp.aml.h4': '4. Sanctions Screening',
            'comp.aml.c4': 'Apex Capital screens all investors and counterparties against major sanctions lists, including those maintained by the United Nations, China, U.S. OFAC, and the European Union. Matches are rejected and reported to regulators as required.',
            'comp.aml.h5': '5. Record Keeping',
            'comp.aml.c5': 'All customer identity records, transaction records, and due diligence files are retained for a minimum of 5 years from the date of termination of the business relationship or the date of the transaction, to satisfy regulatory examination requirements.',
            'comp.aml.h6': '6. Employee Training',
            'comp.aml.c6': 'All employees must complete annual AML training covering regulatory updates, red-flag indicators, and suspicious transaction reporting procedures. New hires must complete initial training within 30 days of onboarding.',
            'comp.aml.h7': '7. Independent Audit',
            'comp.aml.c7': 'The AML program is subject to an independent external audit annually. Audit findings are reported to the Board of Directors and regulatory authorities.',
            'comp.aml.h8': '8. Contact',
            'comp.aml.c8': 'For inquiries or to report suspicious activity, please contact the AML Compliance Officer:<br>Email: longvv810@gmail.com',

            'comp.terms.title': 'Terms of Use',
            'comp.terms.date': '<strong>Effective Date:</strong> January 1, 2025',
            'comp.terms.intro': 'By accessing this website and the services provided by Apex Capital Management Ltd. ("Apex Capital," "we," "us"), you agree to be bound by these Terms of Use. If you do not agree, please refrain from using this website.',
            'comp.terms.h1': '1. No Investment Advice',
            'comp.terms.c1': 'The content on this website is provided for informational purposes only and does not constitute investment advice, a solicitation, or an offer to buy or sell any financial product. Past performance is not indicative of future results. You should consult a qualified financial advisor before making investment decisions.',
            'comp.terms.h2': '2. Accuracy of Information',
            'comp.terms.c2': 'While we strive to ensure the accuracy and timeliness of information on this website, we make no warranties or representations, express or implied, regarding the completeness, accuracy, or reliability of any content. Market data, fund performance figures, and regulatory filings may be subject to updates without notice.',
            'comp.terms.h3': '3. Intellectual Property',
            'comp.terms.c3': 'All content on this website, including text, graphics, logos, icons, and software, is the property of Apex Capital or its content suppliers and is protected by applicable intellectual property laws. Unauthorized reproduction, distribution, or modification of any content is prohibited without prior written consent.',
            'comp.terms.h4': '4. Limitation of Liability',
            'comp.terms.c4': 'To the fullest extent permitted by law, Apex Capital shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your access to or use of this website, including but not limited to any errors or omissions in content, or any loss or damage resulting from reliance on information provided herein.',
            'comp.terms.h5': '5. Third-Party Links',
            'comp.terms.c5': 'This website may contain links to third-party websites for your convenience. Apex Capital does not endorse or assume responsibility for the content, privacy policies, or practices of any third-party sites. Accessing such links is at your own risk.',
            'comp.terms.h6': '6. Privacy',
            'comp.terms.c6': 'Your use of this website is also governed by our Privacy Policy, which outlines how we collect, use, and protect your personal data. Please review the Privacy Policy for more information.',
            'comp.terms.h7': '7. Governing Law',
            'comp.terms.c7': 'These Terms of Use shall be governed by and construed in accordance with the laws of the People\'s Republic of China. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts of Xiamen, Fujian Province.',
            'comp.terms.h8': '8. Modifications',
            'comp.terms.c8': 'We reserve the right to modify these Terms of Use at any time. Changes will be effective immediately upon posting to this website. Your continued use of the website constitutes acceptance of the revised terms.',
            'comp.terms.h9': '9. Contact',
            'comp.terms.c9': 'For questions regarding these Terms of Use, please contact us at:<br>Email: longvv810@gmail.com',

            // Announcements
            'ann.qgef.badge': 'New Fund Launch',
            'ann.qgef.title': 'Quantum Green Energy Fund',
            'ann.qgef.date': 'June 15, 2026',
            'ann.qgef.location': 'Xiamen, China',
            'ann.qgef.readtime': '5 min read',
            'ann.qgef.p1': 'Apex Capital is proud to announce the launch of the <strong>Quantum Green Energy Fund</strong>, a thematic investment vehicle focused on the global energy transition. The fund targets high-growth opportunities across solar, wind, energy storage, and hydrogen value chains, combining quantitative screening with fundamental analysis.',
            'ann.qgef.card1.val': '$5,000',
            'ann.qgef.card1.label': 'Minimum Subscription',
            'ann.qgef.card2.val': '10%–13.5%',
            'ann.qgef.card2.label': 'Target Annual Return',
            'ann.qgef.card3.val': 'T+30',
            'ann.qgef.card3.label': 'Redemption Cycle',
            'ann.qgef.card4.val': 'Global',
            'ann.qgef.card4.label': 'Investment Universe',
            'ann.qgef.h2': 'Investment Strategy',
            'ann.qgef.p2': 'The fund employs a multi-factor quantitative model to screen over 800 listed companies in the clean energy sector worldwide. The portfolio is concentrated in 30–50 high-conviction positions, rebalanced quarterly. Risk management includes sector exposure caps at 25% and single-position limits at 8%.',
            'ann.qgef.h3': 'Key Milestones',
            'ann.qgef.t1.title': 'Q3 2026 — Fund Inception',
            'ann.qgef.t1.desc': 'Initial capital deployment with seed investors; target AUM of $100M by year-end.',
            'ann.qgef.t2.title': 'Q4 2026 — Portfolio Expansion',
            'ann.qgef.t2.desc': 'Expand into emerging market clean energy equities and green bond allocations.',
            'ann.qgef.t3.title': 'Q2 2027 — Institutional Onboarding',
            'ann.qgef.t3.desc': 'Open to institutional investors with customized share classes and reporting.',

            'ann.tih.badge': 'Strategic Partnership',
            'ann.tih.title': 'Tech Innovation Hub Alliance',
            'ann.tih.date': 'May 8, 2026',
            'ann.tih.location': 'Shenzhen, China',
            'ann.tih.readtime': '4 min read',
            'ann.tih.p1': 'Apex Capital has entered into a strategic partnership with the <strong>Tech Innovation Hub</strong>, a leading fintech accelerator based in Shenzhen. This collaboration aims to integrate cutting-edge artificial intelligence and machine learning capabilities into our investment research and risk management platforms.',
            'ann.tih.partner1': 'Apex Capital',
            'ann.tih.partner2': 'Tech Innovation Hub',
            'ann.tih.h2': 'Partnership Scope',
            'ann.tih.hl.title': 'Key Initiatives',
            'ann.tih.hl.li1': 'AI-powered credit risk modeling for bond and bill portfolios',
            'ann.tih.hl.li2': 'Natural language processing for regulatory filing analysis',
            'ann.tih.hl.li3': 'Real-time market sentiment dashboard for trading desks',
            'ann.tih.hl.li4': 'Blockchain-based settlement prototype for interbank CD transactions',
            'ann.tih.p2': 'The partnership grants Apex Capital access to a talent pool of over 200 AI researchers and engineers, along with state-of-the-art GPU computing infrastructure. In return, Apex Capital will provide real-world financial datasets and domain expertise to help validate and commercialize the Hub\'s research.',
            'ann.tih.h3': 'Expected Outcomes',
            'ann.tih.p3': 'Within the first 12 months, we expect to deploy an AI-assisted credit screening module that reduces manual review time by 60% while improving default prediction accuracy. The NLP system will monitor over 5,000 regulatory filings per day across Chinese and English sources for compliance and investment signals.',

            'ann.ic.badge': 'Conference',
            'ann.ic.title': '2026 China Asset Management Summit',
            'ann.ic.date': 'September 12–14, 2026',
            'ann.ic.location': 'Xiamen Int\'l Conference Center',
            'ann.ic.readtime': '3 min read',
            'ann.ic.p1': 'Apex Capital will participate as a <strong>Gold Sponsor</strong> at the 2026 China Asset Management Summit, the premier gathering of asset managers, institutional investors, and regulators in the region. With over 3,000 attendees expected, the three-day event will feature keynote addresses, panel discussions, and closed-door roundtables on the future of asset management.',
            'ann.ic.h2': 'Our Sessions',
            'ann.ic.th1': 'Time',
            'ann.ic.th2': 'Session',
            'ann.ic.th3': 'Speaker',
            'ann.ic.th4': 'Format',
            'ann.ic.s1.time': 'Sep 12, 10:00 AM',
            'ann.ic.s1.title': 'Fixed Income Innovation: Bills & Bonds in the New Rate Regime',
            'ann.ic.s1.speaker': 'CIO, Apex Capital',
            'ann.ic.s1.format': 'Keynote',
            'ann.ic.s2.time': 'Sep 13, 2:00 PM',
            'ann.ic.s2.title': 'AI-Driven Credit Analysis: From Theory to Production',
            'ann.ic.s2.speaker': 'Head of Quant Research',
            'ann.ic.s2.format': 'Panel',
            'ann.ic.s3.time': 'Sep 14, 9:00 AM',
            'ann.ic.s3.title': 'ESG Integration in Fixed Income Portfolios',
            'ann.ic.s3.speaker': 'Head of ESG Strategy',
            'ann.ic.s3.format': 'Workshop',
            'ann.ic.h3': 'Visit Our Booth',
            'ann.ic.p2': 'Attendees are invited to visit Apex Capital at <strong>Booth A-12</strong> in the main exhibition hall. Our team will be available for one-on-one consultations, product demonstrations, and live portfolio analytics. Complimentary copies of our flagship research report, <em>"The Future of Bill & Bond Strategies in China,"</em> will be available.',

            'ann.ck.badge': 'Keynote',
            'ann.ck.title': 'Future of Digital Assets',
            'ann.ck.date': 'April 22, 2026',
            'ann.ck.location': 'Hong Kong Convention Centre',
            'ann.ck.readtime': '6 min read',
            'ann.ck.p1': 'At the 2026 Digital Finance Forum in Hong Kong, Apex Capital\'s CEO delivered a widely anticipated keynote on the institutional adoption of digital assets and the transformative role of blockchain technology in traditional finance. The speech outlined a pragmatic roadmap for integrating digital assets into regulated fund structures.',
            'ann.ck.quote': '"Digital assets are no longer a niche experiment — they are becoming a structural component of the global financial system. The question is not whether to engage, but how to do so with the same rigor and fiduciary discipline we apply to every other asset class."',
            'ann.ck.quoteAuthor': '— Apex Capital CEO, 2026 Digital Finance Forum',
            'ann.ck.h2': 'Market Outlook',
            'ann.ck.stat1': 'Global Digital Asset Market Cap (2026E)',
            'ann.ck.stat2': 'Institutions With Some Exposure by 2028',
            'ann.ck.stat3': 'Recommended Portfolio Allocation',
            'ann.ck.stat4': 'Regulated Digital Asset ETFs Launched (2025–26)',
            'ann.ck.h3': 'Apex Capital\'s Approach',
            'ann.ck.p2': 'The keynote outlined a three-phase approach: <strong>Phase 1 (2026)</strong> — research and education, building internal expertise; <strong>Phase 2 (2027)</strong> — pilot allocations in select managed accounts with strict exposure limits; <strong>Phase 3 (2028+)</strong> — dedicated digital asset fund products subject to regulatory approval. All initiatives will operate within existing compliance frameworks, including AML/KYC, custody segregation, and independent audit.',
            'ann.ck.video': 'Full Keynote Recording (48 min)',
            'ann.ck.p3': 'A full transcript and the accompanying slide deck are available for download. For institutional investors interested in early-access research on digital asset integration strategies, please contact our Investor Relations team.',

            // Contact - index
            'contact.title': 'Get In Touch',
            'contact.subtitle': 'Connect with our team through the channels below.',
            'contact.hq.label': 'Location',
            'contact.hq.value': '82 Zhanhong Rd, Financial Center Tower, 8F/12F/15F, Siming District, Xiamen, China',
            'contact.phone.label': 'Phone',
            'contact.email.label': 'Email',
            'contact.hours.label': 'Business Hours',
            'contact.hours.value': 'Mon-Fri 9:00-18:00 (GMT+8)',
            'contact.social.title': 'Connect With Us',

            // Footer
            'footer.tagline': 'Driving financial innovation with integrity and technology.',
            'footer.rights': 'All rights reserved.',
            'footer.privacy': 'Privacy',
            'footer.terms': 'Terms',
            'footer.disclosures': 'Disclosures',

            // regulatory-filings.html
            'reg.pageTitle': 'Regulatory Filings & Financial Reports',
            'reg.pageSubtitle': 'Complete archive of all regulatory documents, financial statements, audit reports, and investor materials.',
            'reg.breadcrumb.home': 'Home',
            'reg.breadcrumb.disclosure': 'Disclosure',
            'reg.breadcrumb.current': 'Regulatory Filings',
            'reg.filter.year': 'Filter by Year',
            'reg.filter.type': 'Filter by Type',
            'reg.filter.allYears': 'All Years',
            'reg.filter.allTypes': 'All Types',
            'reg.filter.annual': 'Annual Reports',
            'reg.filter.quarterly': 'Quarterly Reports',
            'reg.filter.audit': 'Audit Reports',
            'reg.filter.regulatory': 'Regulatory Filings',
            'reg.filter.investor': 'Investor Materials',
            'reg.archive.title': 'Historical Archives',
            'reg.archive.desc': 'For reports dated prior to 2024, please contact our Investor Relations department at',
            'reg.archive.contact': 'or call +86 592 6888 8888 ext. 201.',
            'btn.viewOnline': 'View Online',
            'published': 'Published',
            'reg.noMatch': 'No Matching Reports',
            'reg.noMatch.desc': 'No reports match the current filter criteria. Try selecting a different year or type.',
            'reg.noData': 'No Reports Found',
            'reg.noData.desc': 'Add PDF files to the regulatory-docs folder on your computer, then run <code>node generate-reports.js</code> to update.',

            // services.html
            'svc.pageTitle': 'Our Services',
            'svc.pageSubtitle': 'Comprehensive fund management solutions powered by cutting-edge technology and deep financial expertise.',
            'svc.breadcrumb.current': 'Services',
            'svc.qs.title': 'Quantitative Strategies',
            'svc.qs.intro': 'Our proprietary algorithms and machine learning models identify market inefficiencies and generate alpha across diverse asset classes.',
            'svc.qs.f1.title': 'Algorithmic Trading',
            'svc.qs.f1.desc': 'High-frequency and mid-frequency trading strategies leveraging real-time market data and predictive analytics.',
            'svc.qs.f2.title': 'Machine Learning Models',
            'svc.qs.f2.desc': 'Deep neural networks and reinforcement learning for pattern recognition and market prediction.',
            'svc.qs.f3.title': 'Statistical Arbitrage',
            'svc.qs.f3.desc': 'Pairs trading and mean-reversion strategies exploiting temporary market dislocations.',
            'svc.qs.f4.title': 'Factor-Based Investing',
            'svc.qs.f4.desc': 'Multi-factor models targeting value, momentum, quality, and low volatility premiums.',
            'svc.si.title': 'Sustainable Investing',
            'svc.si.intro': 'ESG-integrated portfolios that align financial performance with positive environmental and social impact.',
            'svc.si.f1.title': 'Green Energy Fund',
            'svc.si.f1.desc': 'Investments in renewable energy, clean technology, and sustainable infrastructure projects worldwide.',
            'svc.si.f2.title': 'ESG Integration',
            'svc.si.f2.desc': 'Comprehensive environmental, social, and governance screening integrated into every investment decision.',
            'svc.si.f3.title': 'Impact Measurement',
            'svc.si.f3.desc': 'Quantifiable metrics tracking carbon reduction, social benefits, and governance improvements.',
            'svc.si.f4.title': 'Climate Transition Strategies',
            'svc.si.f4.desc': 'Portfolios positioned for the global transition to a low-carbon economy.',
            'svc.rm.title': 'Risk-Managed Solutions',
            'svc.rm.intro': 'Dynamic hedging and portfolio construction designed to protect capital while capturing upside potential.',
            'svc.rm.f1.title': 'Dynamic Hedging',
            'svc.rm.f1.desc': 'Real-time portfolio insurance using options, futures, and volatility instruments to limit downside risk.',
            'svc.rm.f2.title': 'Tail Risk Protection',
            'svc.rm.f2.desc': 'Strategies designed to protect against extreme market events and black swan scenarios.',
            'svc.rm.f3.title': 'Multi-Asset Allocation',
            'svc.rm.f3.desc': 'Strategic and tactical asset allocation across equities, fixed income, commodities, and alternatives.',
            'svc.rm.f4.title': 'Stress Testing & Scenario Analysis',
            'svc.rm.f4.desc': 'Rigorous portfolio stress testing against historical and hypothetical market scenarios.',
            'svc.wm.title': 'Wealth Management',
            'svc.wm.intro': 'Personalized wealth management services for high-net-worth individuals, families, and institutions.',
            'svc.wm.f1.title': 'Portfolio Management',
            'svc.wm.f1.desc': 'Customized investment portfolios aligned with your risk tolerance, time horizon, and financial goals.',
            'svc.wm.f2.title': 'Family Office Services',
            'svc.wm.f2.desc': 'Comprehensive wealth planning, estate structuring, and intergenerational wealth transfer strategies.',
            'svc.wm.f3.title': 'Institutional Advisory',
            'svc.wm.f3.desc': 'Endowment, foundation, and pension fund management with a focus on long-term sustainable returns.',
            'svc.wm.f4.title': 'Alternative Investments',
            'svc.wm.f4.desc': 'Access to private equity, venture capital, hedge funds, and real asset opportunities.',
            'svc.cta.title': 'Ready to Get Started?',
            'svc.cta.desc': 'Schedule a consultation with our team to discuss how Apex Capital can help you achieve your financial objectives.',
            'svc.cta.btn': 'Contact Us',

            // Fund Product
            'fund.name': 'Fujian Shang Jin Nong Sui Stable Income Commercial Paper & Bond Fund',
            'fund.subtitle': 'Hybrid Note-Type Investment Fund · Stable Returns · Daily Subscription/Redemption',
            'fund.breadcrumb': 'Fund Product',
            'fund.summary': 'Hybrid Note-Type Investment Fund | Code: MIN:FJMIN818815839K | Open-Ended Contractual | Daily Open',
            'fund.viewFull': 'View Full Prospectus',
            'fund.hl1.title': '"Fixed Income+" Stable Strategy',
            'fund.hl1.desc': '≥90% allocation to high-grade credit, interest rate bonds & interbank CDs. Target annualized return 13.5%.',
            'fund.hl2.title': 'Fujian Regional Selection',
            'fund.hl2.desc': 'State-owned banks & institutional platform AAA+ notes. T+6 flexible redemption. No redemption fee after 30 days.',
            'fund.hl3.title': 'Strict Risk Control',
            'fund.hl3.desc': 'Dynamic stop-loss at 2.5%. Independent bank risk committee oversight. Minimum subscription from $5,000.',
            'fund.positioning.title': 'Product Positioning',
            'fund.positioning.desc': 'The Shang Jin Nong Sui Stable Income series is designed as a liquid, risk-controlled, steady-return wealth management alternative for investors seeking yields above bank deposit rates with limited volatility tolerance.',
            'fund.highlights.title': 'Core Highlights',
            'fund.h1.title': 'Stability First',
            'fund.h1.desc': 'Adopts a "Fixed Income+" strategy with ≥90% allocation to high-grade credit, interest rate bonds and interbank CDs to ensure stable base returns.',
            'fund.h2.title': 'Flexible Yield Enhancement',
            'fund.h2.desc': 'Institutional participation in national rollover bills and new bill aggregation, capturing market opportunities while controlling position sizes for long-term outperformance.',
            'fund.h3.title': 'Fujian Regional Advantage',
            'fund.h3.desc': 'Leveraging local advantages to select state-owned banks, institutional platforms, and leading enterprise commercial paper in Fujian and coastal economic zones for regional credit premiums.',
            'fund.h4.title': 'Daily Liquidity',
            'fund.h4.desc': 'T+6 redemption confirmation with superior liquidity compared to most bank wealth management products, meeting needs for family reserves and working capital management.',
            'fund.benchmark.title': 'Benchmark & Target',
            'fund.benchmark.label': 'Performance Benchmark',
            'fund.benchmark.value': 'BOC Bill-Bond Composite Wealth Index × 85% + CIB International 100 Index × 15%',
            'fund.target.label': 'Return Target',
            'fund.target.value': 'Annualized return 13.5% (with annual drawdown ≤ 3%)',
            'fund.risk.title': 'Risk Control',
            'fund.risk.1': 'Bill investments limited to state-owned banks and institutional platforms rated AAA+ or above. Private enterprise bills are prohibited.',
            'fund.risk.2': 'Dynamic stop-loss: mandatory redemption if cumulative portfolio drawdown reaches 2.5%.',
            'fund.risk.3': 'Oversight by independent bank risk control committee',
            'fund.audience.title': 'Suitable Investors',
            'fund.audience.1': 'Investors with risk tolerance C2 (Stable) and above',
            'fund.audience.2': 'Individuals or families seeking stable growth with idle funds for 6+ months',
            'fund.audience.3': 'Small business owners, retirees, and those saving for education, marriage funds with clear goals',
            'fund.facts.title': 'Key Facts at a Glance',
            'fund.facts.min': 'Minimum Subscription',
            'fund.facts.min.val': '$5,000 (low entry, suitable for regular investment plans)',
            'fund.facts.return': 'Return Rate',
            'fund.facts.return.val': '10% - 13.5% p.a.',
            'fund.facts.lockup': 'Lock-up Period',
            'fund.facts.lockup.val': 'None. Daily subscription and redemption available.',
            'fund.facts.mgmtFee': 'Management Fee',
            'fund.facts.mgmtFee.val': '0.60% / year',
            'fund.facts.custodyFee': 'Custody Fee',
            'fund.facts.custodyFee.val': '0.10% / year',
            'fund.facts.redemption': 'Redemption Fee',
            'fund.facts.redemption.val': 'Free if held ≥ 30 days',
            'fund.manager.title': 'Fund Manager',
            'fund.manager.name': 'Fujian Shang Jin Nong Sui Stable Income Fund Management Co., Ltd.',
            'fund.manager.established': 'Established: 2001 (approved by Agricultural Bank of China Institutional Management Co., Ltd.)',
            'fund.manager.address': 'Address: Floors 8F/12F/15F, Financial Center Building, No. 82 Zhanhong Road, Siming District, Xiamen',
            'fund.manager.team': 'Core Team: Fixed income team with average 16 years of experience. Key members previously at Agricultural Bank of China, Fujian Rural Commercial Bank, Xiamen International Bank, China Southern Fund, etc.',
            'fund.manager.aum': 'AUM (as of end-2025): Approximately RMB 8.2 billion (fixed income products account for 80%)',
            'fund.filing.title': 'Reference Documents',
            'fund.disclaimer.title': 'Notice',
            'fund.disclaimer.desc': 'Investors should carefully read the CSRC-registered fund contract, prospectus, and the Fujian Shang Jin Nong Sui Stable Income Fund Prospectus. Electronic copies available via email.',
            'fund.disclaimer.tagline': 'Rooted in Fujian, steady every step of the way.'
        },
        zh: {
            // Nav
            'nav.home': '首頁',
            'nav.products': '核心產品',
            'nav.about': '關於我們',
            'nav.services': '服務項目',
            'nav.disclosure': '資訊揭露',
            'nav.contact': '聯絡我們',

            // Hero - index
            'hero.heading': '創新<span class="highlight">未來</span>金融',
            'hero.subtitle': 'Apex Capital 是一家領先的基金管理公司，專注於量化策略、AI 驅動投資和可持續增長機會。',
            'hero.cta': '探索我們的願景',
            'hero.cta2': '查看完整說明書 <i class="fas fa-arrow-right"></i>',
            'hero.stat1.label': '管理規模 (RMB)',
            'hero.stat1.unit': '億',
            'hero.stat2.label': '年化收益目標',
            'hero.stat3.label': '成立年份',
            'hero.card.title': '核心產品',
            'hero.card.mgmtFee': '管理費',
            'hero.card.custodyFee': '託管費',
            'hero.card.min': '起投金額',
            'hero.card.purchase': '申贖',
            'hero.card.daily': '每日開放',

            // Products section
            'products.tag': '核心項目',
            'products.title': '我們的產品',
            'products.subtitle': '專注票據與債券，以穩健策略為您創造持續價值。',
            'products.featured.badge': '主力產品',
            'products.featured.desc': '不低於90%資產配置於高等級信用、利率債及同業單，依託福建區域優勢精選國有銀行及機構平台AAA+票據，年化收益目標13.5%。',
            'products.fph1.title': 'AAA+ 信用評級',
            'products.fph1.desc': '僅投國有銀行及機構平台',
            'products.fph2.title': '10%—13.5% 年化',
            'products.fph2.desc': '回撤控制 ≤ 3%',
            'products.fph3.title': 'T+6 靈活申贖',
            'products.fph3.desc': '持有30天免贖回費',
            'products.fph4.title': '$5,000 起投',
            'products.fph4.desc': '低門檻，適用定投',

            // Fund facts (shared)
            'fund.facts.code': '產品代碼',
            'fund.facts.redemption.short': '≥30天 免費',
            'fund.manager.label': '管理人',
            'fund.manager.short': '福建商金農穗',

            // Fund tags
            'fund.tag1': '混合型',
            'fund.tag2': '票據類',
            'fund.tag3': '契約型開放式',
            'fund.tag4': '每日申贖',

            // Services section
            'services.tag': '更多服務',
            'services.title': '專業基金管理方案',
            'services.card1.title': '量化策略',
            'services.card1.desc': '專有演算法和機器學習模型識別市場低效率，創造超額收益。',
            'services.card2.title': '可持續投資',
            'services.card2.desc': 'ESG 整合投資組合，將財務績效與積極的環境及社會影響相結合。',
            'services.card3.title': '風險管理方案',
            'services.card3.desc': '動態對沖和投資組合構建，保護資本的同時捕捉上行潛力。',
            'services.learnMore': '了解更多',

            // Section tags
            'about.tag': '關於我們',
            'disclosure.tag': '資訊揭露',
            'contact.tag': '聯絡我們',

            // About - index
            'about.title': '核心業務',
            'about.subtitle': '我們將尖端科技與深厚的金融專業知識相結合，為客戶創造卓越回報。',
            'about.card1.title': '量化策略',
            'about.card1.desc': '專有演算法和機器學習模型識別市場低效率，在各類資產中創造超額收益。',
            'about.card2.title': '可持續投資',
            'about.card2.desc': 'ESG 整合投資組合，將財務績效與積極的環境及社會影響相結合。',
            'about.card3.title': '風險管理方案',
            'about.card3.desc': '動態對沖和投資組合構建，旨在保護資本的同時捕捉上行潛力。',

            // Disclosure - index
            'disclosure.title': '公司揭露',
            'disclosure.subtitle': '透明度和合規性是我們營運的核心。',
            'disclosure.card1.title': '監管申報文件',
            'disclosure.card1.li1': '2025 年度報告 – ',
            'disclosure.card1.li1.link': '下載 PDF',
            'disclosure.card1.li2': '2026 年第一季績效更新 – ',
            'disclosure.card1.li2.link': '線上看',
            'disclosure.card1.li3': 'SEC Form ADV – ',
            'disclosure.card1.li3.link': '查閱',
            'disclosure.card1.li4': '經審計財務報表 – ',
            'disclosure.card1.li4.link': '下載',
            'disclosure.card1.more': '查看更多文件',
            'disclosure.card2.title': '合規與治理',
            'disclosure.card2.li1': '道德準則 – ',
            'disclosure.card2.li1.link': '閱讀',
            'disclosure.card2.li2': '隱私政策 – ',
            'disclosure.card2.li2.link': '了解更多',
            'disclosure.card2.li3': '利益衝突政策 – ',
            'disclosure.card2.li3.link': '查閱',
            'disclosure.card2.li4': '反洗錢聲明 – ',
            'disclosure.card2.li4.link': '詳情',
            'disclosure.card3.title': '公告事項',
            'disclosure.card3.li1': '新基金發行：量子綠色能源基金 – ',
            'disclosure.card3.li1.link': '新聞稿',
            'disclosure.card3.li2': '與科技創新中心合作 – ',
            'disclosure.card3.li2.link': '公告',
            'disclosure.card3.li3': '行業會議參與 – ',
            'disclosure.card3.li3.link': '日程',
            'disclosure.card3.li4': 'CEO 主題演講：數位資產的未來 – ',
            'disclosure.card3.li4.link': '觀看錄影',

            // Compliance Pages
            'comp.ethics.title': '道德準則',
            'comp.ethics.date': '<strong>生效日期：</strong>2025 年 1 月 1 日',
            'comp.ethics.intro': 'Apex Capital 及其管理基金致力於以最高道德標準開展業務。本道德準則為全體員工、管理層及合作夥伴確立行為基準，確保每一項決策均以投資者利益為先。',
            'comp.ethics.h1': '1. 誠信與正直',
            'comp.ethics.c1': '全體員工須恪守誠信原則，嚴禁任何形式的欺詐、誤導或不實陳述。所有投資建議、產品宣傳及客戶溝通均須真實、準確、完整。',
            'comp.ethics.h2': '2. 投資者利益優先',
            'comp.ethics.c2': '<ul><li>始終將投資者利益置於公司及個人利益之上</li><li>公平對待所有投資者，不得對特定投資者給予優惠待遇</li><li>交易執行須遵循最佳執行原則，確保最優價格與最小成本</li></ul>',
            'comp.ethics.h3': '3. 利益衝突管理',
            'comp.ethics.c3': '全體員工須主動披露任何實際或潛在的利益衝突，包括但不限於：個人投資、外部商業利益、親屬關係涉及交易對手等。詳見《利益衝突政策》。',
            'comp.ethics.h4': '4. 內幕交易禁止',
            'comp.ethics.c4': '嚴禁利用未公開信息進行個人交易或向他人洩露。所有員工須遵守交易申報制度，並接受合規部門的審查。',
            'comp.ethics.h5': '5. 禮品與招待',
            'comp.ethics.c5': '不得接受任何可能影響或看似影響商業決策的禮品、款待或其他利益。單次接受禮品價值不得超過人民幣 500 元，且須向合規部門申報。',
            'comp.ethics.h6': '6. 舉報機制',
            'comp.ethics.c6': '任何人發現違反本準則之行為，可通過保密渠道向合規部門舉報。公司嚴禁對善意舉報者進行任何形式的報復。',
            'comp.ethics.h7': '7. 違規處理',
            'comp.ethics.c7': '違反本準則者將面臨紀律處分，包括但不限於警告、停職、解除勞動關係，情節嚴重者將移交監管機構處理。',
            'comp.ethics.footer': '<em>本準則每年檢討一次，由董事會轄下合規委員會負責審議修訂。</em>',

            'comp.privacy.title': '隱私政策',
            'comp.privacy.date': '<strong>生效日期：</strong>2025 年 1 月 1 日',
            'comp.privacy.intro': 'Apex Capital（「我們」）重視您的隱私權。本隱私政策說明我們如何收集、使用、儲存及保護您的個人資料。',
            'comp.privacy.h1': '1. 資料收集',
            'comp.privacy.c1': '我們可能收集以下類別的個人資料：<ul><li><strong>身份資料：</strong>姓名、身份證號碼、護照號碼、出生日期</li><li><strong>聯絡資料：</strong>地址、電話號碼、電子郵件</li><li><strong>財務資料：</strong>銀行賬戶信息、收入證明、資產狀況、投資經驗</li><li><strong>交易資料：</strong>申購、贖回記錄、持倉信息</li><li><strong>盡職調查資料：</strong>反洗錢（AML）及認識你的客戶（KYC）所需信息</li></ul>',
            'comp.privacy.h2': '2. 資料使用',
            'comp.privacy.c2': '您的個人資料僅用於以下目的：<ul><li>處理基金申購、贖回及分紅</li><li>履行法律及監管義務（包括反洗錢審查）</li><li>提供客戶服務及產品資訊</li><li>風險管理及內部審計</li></ul>',
            'comp.privacy.h3': '3. 資料共享',
            'comp.privacy.c3': '我們不會向第三方出售您的個人資料。在以下情況下，我們可能共享您的資料：<ul><li>向監管機構、交易所及執法部門依法提供</li><li>向為我們提供服務的合作夥伴（如託管銀行、審計師）提供，該等夥伴受同等保密義務約束</li><li>經您明確同意的其他情況</li></ul>',
            'comp.privacy.h4': '4. 資料安全',
            'comp.privacy.c4': '我們採取合理的技術及管理措施保護您的個人資料，包括數據加密、訪問控制、定期安全審計。數據存儲於境內伺服器，跨境傳輸須經合規審批。',
            'comp.privacy.h5': '5. 資料保存',
            'comp.privacy.c5': '個人資料保存期限為業務關係終止後至少 7 年，以符合監管要求。期限屆滿後將安全銷毀。',
            'comp.privacy.h6': '6. 您的權利',
            'comp.privacy.c6': '<ul><li>查閱及更正您的個人資料</li><li>限制或反對資料處理</li><li>撤回同意（不影響撤回前已進行的合法處理）</li><li>向監管機構投訴</li></ul>',
            'comp.privacy.h7': '7. 聯繫我們',
            'comp.privacy.c7': '如有隱私相關查詢，請聯繫合規部：<br>電郵：longvv810@gmail.com',

            'comp.conflict.title': '利益衝突政策',
            'comp.conflict.date': '<strong>生效日期：</strong>2025 年 1 月 1 日',
            'comp.conflict.intro': 'Apex Capital 致力於識別、管理和披露所有實際及潛在的利益衝突，確保投資者權益不受損害。',
            'comp.conflict.h1': '1. 利益衝突的類型',
            'comp.conflict.c1': '以下為本基金業務中可能出現的利益衝突情形：<ul><li><strong>個人交易：</strong>員工個人投資與基金投資標的重疊</li><li><strong>關聯交易：</strong>與關聯方（如管理人或其子公司）進行的交易</li><li><strong>軟性佣金：</strong>接受交易對手提供的研究服務或其他利益</li><li><strong>多重角色：</strong>同一人員同時服務於多個基金或客戶</li><li><strong>禮品與招待：</strong>接受可能影響獨立判斷的饋贈</li><li><strong>外部任職：</strong>員工在外部機構兼任職務</li></ul>',
            'comp.conflict.h2': '2. 識別與申報',
            'comp.conflict.c2': '<ul><li>新入職員工須在入職 30 日內完成利益衝突申報</li><li>在職員工每年須更新利益衝突申報表</li><li>發生任何可能構成利益衝突的事件時，須在 5 個工作日內主動申報</li><li>投資決策人員須事前申報個人交易計劃</li></ul>',
            'comp.conflict.h3': '3. 管理措施',
            'comp.conflict.c3': '<ul><li><strong>防火牆制度：</strong>投資決策、交易執行、結算等職能嚴格分離</li><li><strong>限制清單：</strong>合規部門維護受限證券清單，相關人員不得交易</li><li><strong>獨立審批：</strong>關聯交易須經獨立風險管理委員會審批</li><li><strong>公平分配：</strong>交易機會按客戶利益最優原則公平分配</li><li><strong>薪酬設計：</strong>薪酬結構不得鼓勵過度冒險或損害投資者利益</li></ul>',
            'comp.conflict.h4': '4. 披露',
            'comp.conflict.c4': '無法通過內部機制妥善管理的利益衝突，將向受影響的投資者作出明確、充分的披露，並在獲得書面同意後方可繼續相關業務。',
            'comp.conflict.h5': '5. 監督與執行',
            'comp.conflict.c5': '合規部門每年對本政策進行獨立審查。違反本政策的行為將按《道德準則》相關條款處理。',

            'comp.aml.title': '反洗錢聲明',
            'comp.aml.date': '<strong>生效日期：</strong>2025 年 1 月 1 日',
            'comp.aml.intro': 'Apex Capital 嚴格遵守適用的反洗錢（AML）及反恐怖融資（CFT）法律法規，致力於維護金融體系安全，防範非法資金流入。',
            'comp.aml.h1': '1. 監管依據',
            'comp.aml.c1': '本反洗錢計劃依據以下法規建立：<ul><li>《中華人民共和國反洗錢法》</li><li>《金融機構反洗錢規定》</li><li>《金融機構大額交易和可疑交易報告管理辦法》</li><li>金融行動特別工作組（FATF）相關建議</li></ul>',
            'comp.aml.h2': '2. 客戶盡職調查（CDD）',
            'comp.aml.c2': '所有投資者在開戶前須完成以下盡職調查程序：<ul><li>核實身份證明文件（自然人：身份證/護照；機構：營業執照、股權結構）</li><li>識別最終受益人（UBO），穿透至持有 25% 以上權益的自然人</li><li>了解資金來源及財富背景</li><li>根據風險評級實施簡化或強化盡職調查</li></ul>',
            'comp.aml.h3': '3. 交易監控',
            'comp.aml.c3': '<ul><li>對單筆或累計超過人民幣 50,000 元的現金交易進行大額報告</li><li>對可疑交易實行 24 小時內向中國反洗錢監測分析中心報告機制</li><li>對來自高風險國家或地區的交易實施強化審查</li><li>監控頻繁申贖、結構化交易等異常模式</li></ul>',
            'comp.aml.h4': '4. 制裁篩查',
            'comp.aml.c4': 'Apex Capital 對所有投資者及交易對手實施制裁名單篩查，涵蓋聯合國、中國、美國 OFAC、歐盟等主要制裁名單。匹配命中者將被拒絕交易並按監管要求上報。',
            'comp.aml.h5': '5. 記錄保存',
            'comp.aml.c5': '所有客戶身份資料、交易記錄及盡職調查文件保存期限不少於 5 年（自業務關係終止或交易發生之日起計），以滿足監管審查要求。',
            'comp.aml.h6': '6. 員工培訓',
            'comp.aml.c6': '全體員工每年須接受反洗錢培訓，涵蓋法規更新、紅旗指標識別及可疑交易報告程序。新入職員工須在入職 30 日內完成首次培訓。',
            'comp.aml.h7': '7. 獨立審計',
            'comp.aml.c7': '反洗錢計劃每年接受一次獨立外部審計，審計結果向董事會及監管機構報告。',
            'comp.aml.h8': '8. 聯繫我們',
            'comp.aml.c8': '如有疑問或需舉報可疑活動，請聯繫反洗錢合規官：<br>電郵：longvv810@gmail.com',

            'comp.terms.title': '使用條款',
            'comp.terms.date': '<strong>生效日期：</strong>2025 年 1 月 1 日',
            'comp.terms.intro': '訪問本網站及使用 Apex Capital Management Ltd.（「Apex Capital」或「我們」）提供的服務，即表示您同意受本使用條款的約束。如不同意，請勿使用本網站。',
            'comp.terms.h1': '1. 不構成投資建議',
            'comp.terms.c1': '本網站內容僅供參考，不構成投資建議、招攬或要約買賣任何金融產品。過往表現不代表未來結果。在做出投資決策前，您應諮詢合資格的財務顧問。',
            'comp.terms.h2': '2. 資訊準確性',
            'comp.terms.c2': '儘管我們致力於確保本網站資訊的準確性和時效性，我們不對任何內容的完整性、準確性或可靠性作任何明示或暗示的保證或陳述。市場數據、基金表現數據及監管申報文件可能會在不另行通知的情況下更新。',
            'comp.terms.h3': '3. 知識產權',
            'comp.terms.c3': '本網站所有內容，包括文字、圖形、標誌、圖標及軟件，均為 Apex Capital 或其內容供應商的財產，受適用的知識產權法律保護。未經事先書面同意，禁止對任何內容進行未經授權的複製、分發或修改。',
            'comp.terms.h4': '4. 責任限制',
            'comp.terms.c4': '在法律允許的最大範圍內，Apex Capital 不對因您訪問或使用本網站而產生的任何直接、間接、附帶、後果性或懲罰性損害承擔責任，包括但不限於內容中的任何錯誤或遺漏，或因依賴本網站所提供資訊而導致的任何損失或損害。',
            'comp.terms.h5': '5. 第三方鏈接',
            'comp.terms.c5': '本網站可能包含第三方網站的鏈接以供您方便使用。Apex Capital 不對任何第三方網站的內容、隱私政策或做法作出認可或承擔責任。訪問此類鏈接的風險由您自行承擔。',
            'comp.terms.h6': '6. 隱私',
            'comp.terms.c6': '您使用本網站亦受我們的隱私政策管轄，該政策說明了我們如何收集、使用和保護您的個人資料。請查閱隱私政策以獲取更多資訊。',
            'comp.terms.h7': '7. 管轄法律',
            'comp.terms.c7': '本使用條款受中華人民共和國法律管轄並按其解釋。因本條款產生的任何爭議，應提交福建省廈門市有管轄權的法院專屬管轄。',
            'comp.terms.h8': '8. 條款修改',
            'comp.terms.c8': '我們保留隨時修改本使用條款的權利。修改將於本網站發布後立即生效。您繼續使用本網站即表示接受經修訂的條款。',
            'comp.terms.h9': '9. 聯繫我們',
            'comp.terms.c9': '如對本使用條款有任何疑問，請聯繫我們：<br>電郵：longvv810@gmail.com',

            // Announcements
            'ann.qgef.badge': '新基金發行',
            'ann.qgef.title': '量子綠色能源基金',
            'ann.qgef.date': '2026 年 6 月 15 日',
            'ann.qgef.location': '中國廈門',
            'ann.qgef.readtime': '閱讀時間：5 分鐘',
            'ann.qgef.p1': 'Apex Capital 榮幸宣布推出<strong>量子綠色能源基金</strong>，這是一檔專注於全球能源轉型的主題投資工具。該基金結合量化篩選與基本面分析，在太陽能、風能、儲能及氫能價值鏈中捕捉高增長機會。',
            'ann.qgef.card1.val': '$5,000',
            'ann.qgef.card1.label': '最低認購金額',
            'ann.qgef.card2.val': '10%–13.5%',
            'ann.qgef.card2.label': '年化目標收益',
            'ann.qgef.card3.val': 'T+30',
            'ann.qgef.card3.label': '贖回週期',
            'ann.qgef.card4.val': '全球',
            'ann.qgef.card4.label': '投資範圍',
            'ann.qgef.h2': '投資策略',
            'ann.qgef.p2': '該基金採用多因子量化模型，篩選全球清潔能源領域超過 800 家上市公司。組合集中持有 30 至 50 個高確信度倉位，每季度再平衡。風險管理包括行業敞口上限 25% 及單一倉位上限 8%。',
            'ann.qgef.h3': '關鍵里程碑',
            'ann.qgef.t1.title': '2026 Q3 — 基金成立',
            'ann.qgef.t1.desc': '初始資金部署，種子投資者參與；目標年底 AUM 達 1 億美元。',
            'ann.qgef.t2.title': '2026 Q4 — 組合擴展',
            'ann.qgef.t2.desc': '擴展至新興市場清潔能源股票及綠色債券配置。',
            'ann.qgef.t3.title': '2027 Q2 — 機構投資者入場',
            'ann.qgef.t3.desc': '向機構投資者開放，提供定制份額類別及報告服務。',

            'ann.tih.badge': '戰略合作',
            'ann.tih.title': '科技創新中心聯盟',
            'ann.tih.date': '2026 年 5 月 8 日',
            'ann.tih.location': '中國深圳',
            'ann.tih.readtime': '閱讀時間：4 分鐘',
            'ann.tih.p1': 'Apex Capital 與深圳領先的金融科技加速器<strong>科技創新中心</strong>達成戰略合作夥伴關係。此次合作旨在將尖端人工智能和機器學習技術整合到我們的投資研究和風險管理平台。',
            'ann.tih.partner1': 'Apex Capital',
            'ann.tih.partner2': '科技創新中心',
            'ann.tih.h2': '合作範圍',
            'ann.tih.hl.title': '主要計劃',
            'ann.tih.hl.li1': '用於債券及票據組合的 AI 驅動信用風險建模',
            'ann.tih.hl.li2': '用於監管申報文件分析的自然語言處理',
            'ann.tih.hl.li3': '為交易台提供的即時市場情緒儀表板',
            'ann.tih.hl.li4': '基於區塊鏈的同業存單交易結算原型',
            'ann.tih.p2': '此次合作為 Apex Capital 提供超過 200 名 AI 研究人員及工程師的人才庫，以及最先進的 GPU 計算基礎設施。作為回報，Apex Capital 將提供真實金融數據集和領域專業知識，幫助驗證及商業化該中心的研發成果。',
            'ann.tih.h3': '預期成果',
            'ann.tih.p3': '在首 12 個月內，我們預計部署一個 AI 輔助信用篩選模組，將人工審查時間減少 60%，同時提升違約預測準確性。NLP 系統將每日監控超過 5,000 份中英文監管申報文件，提取合規及投資信號。',

            'ann.ic.badge': '行業會議',
            'ann.ic.title': '2026 中國資產管理峰會',
            'ann.ic.date': '2026 年 9 月 12–14 日',
            'ann.ic.location': '廈門國際會議中心',
            'ann.ic.readtime': '閱讀時間：3 分鐘',
            'ann.ic.p1': 'Apex Capital 將以<strong>金牌贊助商</strong>身份參加 2026 中國資產管理峰會，這是區域內資產管理機構、機構投資者及監管機構的頂級盛會。預計超過 3,000 名與會者將參與為期三天的主題演講、專題討論及閉門圓桌會議，探討資產管理的未來。',
            'ann.ic.h2': '我們的議程',
            'ann.ic.th1': '時間',
            'ann.ic.th2': '議程',
            'ann.ic.th3': '講者',
            'ann.ic.th4': '形式',
            'ann.ic.s1.time': '9 月 12 日 上午 10:00',
            'ann.ic.s1.title': '固定收益創新：新利率環境下的票據與債券策略',
            'ann.ic.s1.speaker': 'Apex Capital 投資總監',
            'ann.ic.s1.format': '主題演講',
            'ann.ic.s2.time': '9 月 13 日 下午 2:00',
            'ann.ic.s2.title': 'AI 驅動信用分析：從理論到實踐',
            'ann.ic.s2.speaker': '量化研究主管',
            'ann.ic.s2.format': '專題討論',
            'ann.ic.s3.time': '9 月 14 日 上午 9:00',
            'ann.ic.s3.title': '固定收益組合中的 ESG 整合',
            'ann.ic.s3.speaker': 'ESG 策略主管',
            'ann.ic.s3.format': '工作坊',
            'ann.ic.h3': '參觀我們的展位',
            'ann.ic.p2': '歡迎與會者蒞臨主展廳<strong>A-12 展位</strong>。我們的團隊將提供一對一諮詢、產品演示及即時組合分析。現場可免費獲取我們的旗艦研究報告《中國票據與債券策略的未來》。',

            'ann.ck.badge': '主題演講',
            'ann.ck.title': '數位資產的未來',
            'ann.ck.date': '2026 年 4 月 22 日',
            'ann.ck.location': '香港會議展覽中心',
            'ann.ck.readtime': '閱讀時間：6 分鐘',
            'ann.ck.p1': '在 2026 年香港數位金融論壇上，Apex Capital 執行長發表了備受期待的關於數位資產機構化採用及區塊鏈技術對傳統金融變革性影響的主題演講。演講概述了將數位資產整合到受監管基金結構中的務實路線圖。',
            'ann.ck.quote': '"數位資產已不再是小眾實驗——它們正成為全球金融體系的結構性組成部分。問題不在於是否參與，而在於如何以我們對其他所有資產類別所秉持的同樣嚴謹和受託責任來參與。"',
            'ann.ck.quoteAuthor': '— Apex Capital 執行長，2026 數位金融論壇',
            'ann.ck.h2': '市場展望',
            'ann.ck.stat1': '全球數位資產市值（2026 預估）',
            'ann.ck.stat2': '到 2028 年有配置敞口的機構佔比',
            'ann.ck.stat3': '建議組合配置比例',
            'ann.ck.stat4': '已發行受監管數位資產 ETF（2025–26）',
            'ann.ck.h3': 'Apex Capital 的策略',
            'ann.ck.p2': '演講概述了三個階段的策略：<strong>第一階段（2026）</strong>——研究與教育，建立內部專業能力；<strong>第二階段（2027）</strong>——在特定管理帳戶中進行試點配置，設有嚴格的敞口限制；<strong>第三階段（2028+）</strong>——在監管批准的前提下推出專項數位資產基金產品。所有舉措將在現有合規框架內運作，包括 AML/KYC、資產託管隔離及獨立審計。',
            'ann.ck.video': '完整主題演講錄影（48 分鐘）',
            'ann.ck.p3': '完整演講稿及簡報文件可供下載。對於有意獲取數位資產整合策略早期研究的機構投資者，請聯繫我們的投資者關係團隊。',

            // Contact - index
            'contact.title': '聯絡我們',
            'contact.subtitle': '通過以下渠道與我們的團隊聯繫。',
            'contact.hq.label': '地址',
            'contact.hq.value': '廈門市思明區展鴻路82號金融中心大廈8F/12F/15F',
            'contact.phone.label': '電話',
            'contact.email.label': '電子郵件',
            'contact.hours.label': '營業時間',
            'contact.hours.value': '週一至週五 9:00-18:00 (GMT+8)',
            'contact.social.title': '關注我們',

            // Footer
            'footer.tagline': '以誠信和科技推動金融創新。',
            'footer.rights': '版權所有。',
            'footer.privacy': '隱私權',
            'footer.terms': '條款',
            'footer.disclosures': '揭露事項',

            // regulatory-filings.html
            'reg.pageTitle': '監管申報與財務報告',
            'reg.pageSubtitle': '所有監管文件、財務報表、審計報告和投資者資料的完整檔案庫。',
            'reg.breadcrumb.home': '首頁',
            'reg.breadcrumb.disclosure': '資訊揭露',
            'reg.breadcrumb.current': '監管申報',
            'reg.filter.year': '按年份篩選',
            'reg.filter.type': '按類型篩選',
            'reg.filter.allYears': '所有年份',
            'reg.filter.allTypes': '所有類型',
            'reg.filter.annual': '年度報告',
            'reg.filter.quarterly': '季度報告',
            'reg.filter.audit': '審計報告',
            'reg.filter.regulatory': '監管申報',
            'reg.filter.investor': '投資者資料',
            'reg.archive.title': '歷史檔案',
            'reg.archive.desc': '如需 2024 年之前的報告，請聯繫我們的投資者關係部門：',
            'reg.archive.contact': '或致電 +86 592 6888 8888 轉 201。',
            'btn.viewOnline': '線上看',
            'published': '發布日期',
            'reg.noMatch': '無符合條件的報告',
            'reg.noMatch.desc': '沒有符合當前篩選條件的報告，請嘗試選擇其他年份或類型。',
            'reg.noData': '暫無報告',
            'reg.noData.desc': '將 PDF 文件添加到電腦上的 regulatory-docs 文件夾，然後運行 <code>node generate-reports.js</code> 更新。',

            // services.html
            'svc.pageTitle': '我們的服務',
            'svc.pageSubtitle': '全面的基金管理方案，以尖端科技和深厚的金融專業知識為支撐。',
            'svc.breadcrumb.current': '服務項目',
            'svc.qs.title': '量化策略',
            'svc.qs.intro': '我們的專有演算法和機器學習模型識別市場低效率，在各類資產中創造超額收益。',
            'svc.qs.f1.title': '演算法交易',
            'svc.qs.f1.desc': '利用即時市場數據和預測分析的高頻及中頻交易策略。',
            'svc.qs.f2.title': '機器學習模型',
            'svc.qs.f2.desc': '用於模式識別和市場預測的深度神經網路與強化學習。',
            'svc.qs.f3.title': '統計套利',
            'svc.qs.f3.desc': '利用配對交易和均值回歸策略，捕捉暫時性市場錯位機會。',
            'svc.qs.f4.title': '因子投資',
            'svc.qs.f4.desc': '針對價值、動能、品質和低波動溢酬的多因子模型。',
            'svc.si.title': '可持續投資',
            'svc.si.intro': 'ESG 整合投資組合，將財務績效與積極的環境及社會影響相結合。',
            'svc.si.f1.title': '綠色能源基金',
            'svc.si.f1.desc': '投資於全球可再生能源、清潔技術和可持續基礎設施項目。',
            'svc.si.f2.title': 'ESG 整合',
            'svc.si.f2.desc': '將全面的環境、社會和治理篩選融入每一項投資決策。',
            'svc.si.f3.title': '影響力衡量',
            'svc.si.f3.desc': '追蹤碳減排、社會效益和治理改善的量化指標。',
            'svc.si.f4.title': '氣候轉型策略',
            'svc.si.f4.desc': '為全球低碳經濟轉型佈局的投資組合。',
            'svc.rm.title': '風險管理方案',
            'svc.rm.intro': '動態對沖和投資組合構建，旨在保護資本的同時捕捉上行潛力。',
            'svc.rm.f1.title': '動態對沖',
            'svc.rm.f1.desc': '使用選擇權、期貨和波動率工具進行即時投資組合保險，限制下行風險。',
            'svc.rm.f2.title': '尾部風險保護',
            'svc.rm.f2.desc': '旨在防範極端市場事件和黑天鵝情境的策略。',
            'svc.rm.f3.title': '多元資產配置',
            'svc.rm.f3.desc': '跨股票、固定收益、商品和另類資產的戰略與戰術資產配置。',
            'svc.rm.f4.title': '壓力測試與情境分析',
            'svc.rm.f4.desc': '針對歷史和假設市場情境進行嚴謹的投資組合壓力測試。',
            'svc.wm.title': '財富管理',
            'svc.wm.intro': '為高淨值個人、家族和機構提供個性化的財富管理服務。',
            'svc.wm.f1.title': '投資組合管理',
            'svc.wm.f1.desc': '根據您的風險承受能力、投資期限和財務目標，量身定制投資組合。',
            'svc.wm.f2.title': '家族辦公室服務',
            'svc.wm.f2.desc': '全面的財富規劃、遺產架構和跨代財富傳承策略。',
            'svc.wm.f3.title': '機構諮詢',
            'svc.wm.f3.desc': '捐贈基金、基金會和退休金管理，專注於長期可持續回報。',
            'svc.wm.f4.title': '另類投資',
            'svc.wm.f4.desc': '獲取私募股權、創投、對沖基金和實物資產機會。',
            'svc.cta.title': '準備好開始了嗎？',
            'svc.cta.desc': '與我們的團隊預約諮詢，討論 Apex Capital 如何幫助您實現財務目標。',
            'svc.cta.btn': '聯絡我們',

            // Fund Product
            'fund.name': '福建商金農穗穩盈收益類商票及債券基金',
            'fund.subtitle': '混合型票據類投資基金 · 穩健收益 · 每日開放申贖',
            'fund.breadcrumb': '基金產品',
            'fund.summary': '混合型票據類投資基金 | 產品代碼：閩:FJMIN818815839K | 契約型開放式 | 每日開放申贖',
            'fund.viewFull': '查看完整產品說明書',
            'fund.hl1.title': '"固收+"穩健策略',
            'fund.hl1.desc': '不低於90%資產配置於高等級信用、利率債及同業單，年化收益目標13.5%。',
            'fund.hl2.title': '福建區域精選',
            'fund.hl2.desc': '國有銀行及機構平台AAA+票據，T+6靈活申贖，持有≥30天免贖回費。',
            'fund.hl3.title': '嚴格風控',
            'fund.hl3.desc': '動態止損線2.5%，銀行獨立風控委員會監督，最低認購$5,000元。',
            'fund.positioning.title': '產品定位',
            'fund.positioning.desc': '商金農穗穩盈商票債券系列致力於為投資者打造一款流動性較好、風險可控、收益穩健的理財替代工具。適合希望獲得高於銀行定期存款收益，並能承受有限波動的資金配置需求。',
            'fund.highlights.title': '核心亮點',
            'fund.h1.title': '"穩"字當頭',
            'fund.h1.desc': '採取"固收+"策略，不低於90%的資產配置於高等級信用、利率債及同業單，力求基礎收益穩健。',
            'fund.h2.title': '"重"在增厚，靈活增強',
            'fund.h2.desc': '經營及投資機構參與多項國家展期轉票及新票統匯，在控制體量的前提下捕捉市場機會，力爭長期超越純商票展期收益。',
            'fund.h3.title': '福建區域精選',
            'fund.h3.desc': '依託管理人在地優勢，精選福建及沿海經濟區國有銀行、機構平台、龍頭民生企業商票券，獲取區域信用溢價，並參與各展期回購增加循環複利。',
            'fund.h4.title': '每日開放，申贖靈活',
            'fund.h4.desc': 'T+6確認贖回資金，流動性優於多數銀行理財，滿足家庭備用金、經營周轉資金的靈活管理需求。',
            'fund.benchmark.title': '基準與目標',
            'fund.benchmark.label': '業績比較基準',
            'fund.benchmark.value': '中銀票債綜合財富指數 × 85% + 商銀國際100指數 × 15%',
            'fund.target.label': '收益目標',
            'fund.target.value': '年化收益率 13.5%（控制年度回撤 ≤ 3%）',
            'fund.risk.title': '風控機制',
            'fund.risk.1': '票券投資只選國有銀行、機構平台AAA+及以上信用評級，禁投私企民企票債',
            'fund.risk.2': '設有動態止損線：若組合累計回撤達2.5%，則強制贖回',
            'fund.risk.3': '銀行獨立風控委員會監督',
            'fund.audience.title': '適合人群',
            'fund.audience.1': '風險偏好C2（穩健型）及以上的投資者',
            'fund.audience.2': '希望用6個月以上閒置資金進行穩健增值的個人或家庭',
            'fund.audience.3': '小微企業經營主、退休人士及教育金、婚嫁金等目標明確的儲備者',
            'fund.facts.title': '產品要素速覽',
            'fund.facts.min': '最低認購金額',
            'fund.facts.min.val': '$5,000 元（起投低，適用定投）',
            'fund.facts.return': '收益率',
            'fund.facts.return.val': '年 10% - 13.5%',
            'fund.facts.lockup': '封閉期',
            'fund.facts.lockup.val': '無，每日開放申贖',
            'fund.facts.mgmtFee': '管理費',
            'fund.facts.mgmtFee.val': '0.60% / 年',
            'fund.facts.custodyFee': '托管費',
            'fund.facts.custodyFee.val': '0.10% / 年',
            'fund.facts.redemption': '贖回費率',
            'fund.facts.redemption.val': '持有 ≥ 30 天免贖回費',
            'fund.manager.title': '管理人介紹',
            'fund.manager.name': '福建商金農穗穩盈基金管理有限公司',
            'fund.manager.established': '成立時間：2001年（經中國農業銀行機構管理有限公司批准設立）',
            'fund.manager.address': '辦公地址：廈門市思明區展鴻路82號金融中心大廈8F/12F/15F',
            'fund.manager.team': '核心團隊：固定收益團隊平均從業經驗16年，主要成員任職於中國農業銀行、福建農商銀行、廈門國際銀行、南方基金等機構',
            'fund.manager.aum': '管理規模（截至2025年末）：約82億元人民幣（其中固收類產品占80%）',
            'fund.filing.title': '備查文件',
            'fund.disclaimer.title': '提示',
            'fund.disclaimer.desc': '投資者請仔細閱讀央行關於《範基金合同》《範招募說明書》及我司《福建商金農穗穩盈基金管理有限公司基金招募說明書》領取電子檔郵件。',
            'fund.disclaimer.tagline': '深耕福建，穩健伴您每一步。'
        }
    };

    var currentLang = localStorage.getItem('apex-lang') || 'en';

    function applyTranslations(lang) {
        const data = translations[lang];
        if (!data) return;

        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (data[key]) {
                el.innerHTML = data[key];
            }
        });

        // Update HTML lang attribute
        document.documentElement.lang = lang === 'zh' ? 'zh-Hant' : 'en';

        // Update toggle button text
        const toggleBtn = document.querySelector('.lang-toggle');
        if (toggleBtn) {
            toggleBtn.textContent = lang === 'zh' ? 'EN' : '繁中';
        }

        // Update page title
        if (lang === 'zh') {
            const path = window.location.pathname;
            if (path.includes('quantum-green-energy')) {
                document.title = '量子綠色能源基金 — Apex Capital';
            } else if (path.includes('tech-innovation-hub')) {
                document.title = '科技創新中心聯盟 — Apex Capital';
            } else if (path.includes('industry-conference')) {
                document.title = '2026 中國資產管理峰會 — Apex Capital';
            } else if (path.includes('ceo-keynote')) {
                document.title = '數位資產的未來 — Apex Capital';
            } else if (path.includes('code-of-ethics')) {
                document.title = '道德準則 — Apex Capital';
            } else if (path.includes('privacy-policy')) {
                document.title = '隱私政策 — Apex Capital';
            } else if (path.includes('conflict-of-interest')) {
                document.title = '利益衝突政策 — Apex Capital';
            } else if (path.includes('terms')) {
                document.title = '使用條款 — Apex Capital';
            } else if (path.includes('aml-statement')) {
                document.title = '反洗錢聲明 — Apex Capital';
            } else if (path.includes('regulatory-filings')) {
                document.title = '監管申報與報告 - Apex Capital';
            } else if (path.includes('services')) {
                document.title = '我們的服務 - Apex Capital';
            } else {
                document.title = 'Apex Capital - 創新基金管理';
            }
        } else {
            const path = window.location.pathname;
            if (path.includes('quantum-green-energy')) {
                document.title = 'New Fund Launch: Quantum Green Energy Fund — Apex Capital';
            } else if (path.includes('tech-innovation-hub')) {
                document.title = 'Partnership: Tech Innovation Hub — Apex Capital';
            } else if (path.includes('industry-conference')) {
                document.title = '2026 China Asset Management Summit — Apex Capital';
            } else if (path.includes('ceo-keynote')) {
                document.title = 'CEO Keynote: Future of Digital Assets — Apex Capital';
            } else if (path.includes('code-of-ethics')) {
                document.title = 'Code of Ethics — Apex Capital';
            } else if (path.includes('privacy-policy')) {
                document.title = 'Privacy Policy — Apex Capital';
            } else if (path.includes('conflict-of-interest')) {
                document.title = 'Conflict of Interest Policy — Apex Capital';
            } else if (path.includes('terms')) {
                document.title = 'Terms of Use — Apex Capital';
            } else if (path.includes('aml-statement')) {
                document.title = 'Anti-Money Laundering Statement — Apex Capital';
            } else if (path.includes('regulatory-filings')) {
                document.title = 'Regulatory Filings & Reports - Apex Capital';
            } else if (path.includes('services')) {
                document.title = 'Our Services - Apex Capital';
            } else {
                document.title = 'Apex Capital - Innovative Fund Management';
            }
        }

        localStorage.setItem('apex-lang', lang);
        currentLang = lang;
    }

    function toggleLang() {
        const newLang = currentLang === 'en' ? 'zh' : 'en';
        applyTranslations(newLang);
    }

    // Apply saved language on load
    document.addEventListener('DOMContentLoaded', function() {
        applyTranslations(currentLang);

        // Attach toggle event
        const toggleBtn = document.querySelector('.lang-toggle');
        if (toggleBtn) {
            toggleBtn.addEventListener('click', toggleLang);
        }
    });
    // Expose for dynamic rendering callers
    window.applyTranslations = applyTranslations;
    window.getCurrentLang = function() { return currentLang; };
})();
