// Auto-generated by generate-reports.js on 2026-04-29T11:32:46.085Z
// DO NOT EDIT MANUALLY - Run "node generate-reports.js" to regenerate

var REGULATORY_REPORTS = [
  {
    "year": "2026",
    "filename": "2026 Investor Day Presentation.pdf",
    "path": "regulatory-docs/2026/2026%20Investor%20Day%20Presentation.pdf",
    "title": "2026 Investor Day Presentation",
    "type": "investor",
    "date": "April 29, 2026",
    "size": "1.5 KB",
    "description": ""
  },
  {
    "year": "2026",
    "filename": "Q1 2026 Quarterly Report.pdf",
    "path": "regulatory-docs/2026/Q1%202026%20Quarterly%20Report.pdf",
    "title": "Q1 2026 Quarterly Report",
    "type": "quarterly",
    "date": "April 29, 2026",
    "size": "1.3 KB",
    "description": ""
  },
  {
    "year": "2026",
    "filename": "SEC Form ADV 2026.pdf",
    "path": "regulatory-docs/2026/SEC%20Form%20ADV%202026.pdf",
    "title": "SEC Form ADV 2026",
    "type": "regulatory",
    "date": "April 29, 2026",
    "size": "1.2 KB",
    "description": ""
  },
  {
    "year": "2026",
    "filename": "新建 文本文档.pdf",
    "path": "regulatory-docs/2026/%E6%96%B0%E5%BB%BA%20%E6%96%87%E6%9C%AC%E6%96%87%E6%A1%A3.pdf",
    "title": "新建 文本文档",
    "type": "other",
    "date": "April 29, 2026",
    "size": "0 B",
    "description": ""
  },
  {
    "year": "2025",
    "filename": "Annual Report 2025.pdf",
    "path": "regulatory-docs/2025/Annual%20Report%202025.pdf",
    "title": "Annual Report 2025",
    "type": "annual",
    "date": "April 29, 2026",
    "size": "1.3 KB",
    "description": ""
  },
  {
    "year": "2025",
    "filename": "Audited Financial Statements 2025.pdf",
    "path": "regulatory-docs/2025/Audited%20Financial%20Statements%202025.pdf",
    "title": "Audited Financial Statements 2025",
    "type": "audit",
    "date": "April 29, 2026",
    "size": "1.3 KB",
    "description": ""
  },
  {
    "year": "2026",
    "filename": "test v.pdf",
    "path": "regulatory-docs/2026/test%20v.pdf",
    "title": "Test PDF Document",
    "type": "other",
    "date": "April 22, 2026",
    "size": "458 B",
    "description": "This is a test PDF document for verifying the document display functionality."
  }
];
